name: Build & Push container to github
on:
  push:
    branches:
      - main
  workflow_dispatch:      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: get_tag_name
    outputs:
      new_tag: ${{ steps.get_tag_name.outputs.new_tag }}

  pushit:
    needs: tag
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  
    - name: Echo
      run: echo ${{ steps.tag.outputs.result }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/bcg-checkout:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/bcg-checkout:${{ needs.tag.outputs.new_tag}}